
# Configuraci\u00f3n para JavaFX
jdk.graphics.allowNonStandardPipeline=true
javafx.verbose=false

# Configuraci\u00f3n para Jansi
jansi.passthrough=true
jansi.force=true

# Silencia warnings de JavaFX
javafx.verbose=false
prism.verbose=false

# Configuraci\u00f3n para Unsafe
sun.misc.unsafe.silent=true